Add part7
c-3lab/fiware-learning-handson pull request #15
Opened 2022-08-08 06:45 UTC by TakayasuKoura

part7を作成いたしました。
ご確認お願いいたします。

2022-08-09 02:59 UTC, ryo-ma commented
私の方では問題ありません。ready for reviewにしていただければマージします。

2022-08-10 00:30 UTC, k-oizumi-abel requested changes

2022-08-10 00:33 UTC, TakayasuKoura commented on fiware-part7/step1.md
> +# 1-1 FIWARE OrionとFIWARE CygnusとMongoDBの起動確認
「1-1 環境の起動」に修正いたします。

2022-08-10 00:43 UTC, TakayasuKoura commented on fiware-part7/step1.md
> +![ログ](./assets/7-3.png)
すべてのフィールドに値が入っている１レコードのみに画像を修正いたします。

2022-08-10 00:43 UTC, TakayasuKoura commented on fiware-part7/step1.md
> +![全体構成図](./assets/7-2.png)
縦位置を揃えるよう修正いたします。

2022-08-18 10:29 UTC, Sheile commented on fiware-part7/step1.md
> +一覧に**orion**と**mongodb**と**cygnus**と**postgresql**があれば成功です。
`container_name`の指定があるので微妙に違う名前になりそうですね。

2022-08-18 10:30 UTC, Sheile commented on fiware-part7/step1.md
> +デフォルトのログファイルの出力先は **/tmp/contextBroker.log** です。
パスやコマンドは `**hoge**` ではなく `` `hoge` ``が一般的かと思います。

2022-08-19 05:33 UTC, TakayasuKoura commented on fiware-part7/step1.md
> +一覧に**orion**と**mongodb**と**cygnus**と**postgresql**があれば成功です。
@ryo-ma に相談いたします。対応する場合は全Partを修正いたします。

2022-08-19 05:33 UTC, TakayasuKoura commented on fiware-part7/step1.md
> +デフォルトのログファイルの出力先は **/tmp/contextBroker.log** です。
@ryo-ma に相談いたします。対応する場合は全Partを修正いたします。

2022-08-25 01:38 UTC, merged